area/cloudflare:
  - changed-files:
      - any-glob-to-any-file:
          - "cloudflare/*"
          - "cloudflare/**/*"

area/proxmox:
  - changed-files:
      - any-glob-to-any-file:
          - "proxmox/*"
          - "proxmox/**/*"

area/k8s-hyperion:
  - changed-files:
      - any-glob-to-any-file: "k8s/infrastructure/hyperion/**/*"

area/k8s-cronos:
  - changed-files:
      - any-glob-to-any-file: "k8s/infrastructure/cronos/**/*"

area/argocd:
  - changed-files:
      - any-glob-to-any-file: "k8s/applications/argocd/**/*"

area/fluxcd:
  - changed-files:
      - any-glob-to-any-file: "k8s/applications/fluxcd/**/*"

area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: "k8s/**/*"

area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
