# .github/labeler.yml
cloudflare/*:
  - area/cloudflare

cloudflare/**:
  - area/cloudflare

proxmox/*:
  - area/proxmox

proxmox/**:
  - area/proxmox

k8s/infrastructure/hyperion/**:
  - area/k8s-hyperion

k8s/infrastructure/cronos/**:
  - area/k8s-cronos

k8s/applications/argocd/**:
  - area/argocd

k8s/applications/fluxcd/**:
  - area/fluxcd

k8s/**:
  - area/kubernetes

.github/**:
  - area/github
