area/cloudflare:
  - changed-files:
      - any-glob-to-any-file: "cloudflare/**/*"

area/docker:
  - changed-files:
      - any-glob-to-any-file: "docker/**/*"

area/terraform:
  - changed-files:
      - any-glob-to-any-file: "terraform/**/*"

area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: "kubernetes/**/*"

area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"

target/hyperion:
  - changed-files:
      - any-glob-to-any-file:
          - "terraform/proxmox/infraestructure/hyperion/**/*"
          - "kubernetes/applications/argocd/**/*"

target/cronos:
  - changed-files:
      - any-glob-to-any-file:
          - "terraform/proxmox/infraestructure/cronos/**/*"
          - "kubernetes/applications/fluxcd/**/*"

target/proxmox:
  - changed-files:
      - any-glob-to-any-file:
          - "proxmox/**/*"

target/swarm:
  - changed-files:
      - any-glob-to-any-file:
          - "docker/swarm/**/*"