apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd
spec:
  project: homelab
  sources:
    - repoURL: https://semaphoreui.github.io/charts
      chart: semaphore
      targetRevision: 16.0.0
      helm:
        releaseName: semaphore
        valueFiles:
          - $values/apps/semaphore/values.yaml
    - repoURL: https://gitlab.com/bryansalcedo/homelab-argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
