    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: pocket-route
      namespace: pocket-id
    spec:
      parentRefs:
        - name: cilium-gateway
          namespace: cilium-gateway
          sectionName: "https"
      hostnames:
      - "pocket.home.cervant.net"
      rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - name: pocket-id
            port: 1411