services:
  nexterm:
    image: nexterm/aio:latest
    ports:
      - target: 6989
        published: 6989
        mode: host
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - nexterm_data:/app/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==worker"
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
    networks:
      - swarm-frontend

volumes:
  nexterm_data:

networks:
  swarm-frontend:
    external: true
