apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998

      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
            namespace: external-secrets

      caProvider:
        type: ConfigMap
        name: bw-sdk-ca
        key: ca.pem
        namespace: external-secrets

      organizationID: "6fc16696-8889-499e-8442-b32a0110a471"
      projectID: "67baab9f-e62f-4230-90da-b32a0111dc5c"