apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  labels:
    tier: controllers
    domain: identity
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: homelab
  sources:
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
      chart: infisical-standalone
      targetRevision: 1.6.1
      helm:
        releaseName: infisical-standalone
        valuesObject:
          ingress:
            enabled: false
          postgresql:
            enabled: true
            name: postgresql
            useExistingPostgresSecret: 
              enabled: true
              existingConnectionStringSecret:
                name: infisical-secrets
                key: DB_CONNECTION_URI
          redis:
            enabled: true
            name: redis
            architecture: standalone
            usePassword: false
    - repoURL: https://github.com/Brsalcedom/homelab-iac
      path: k8s/applications/argocd/infisical/manifests
      targetRevision: main
      ref: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true