apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  labels:
    tier: controllers
    domain: identity
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: homelab
  sources:
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
      chart: infisical-standalone
      targetRevision: 1.6.1
      helm:
        releaseName: infisical-standalone
        valueFiles:
          - $values/k8s/applications/argocd/infisical
    - repoURL: https://github.com/Brsalcedom/homelab-iac
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true