apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  labels:
    tier: controllers
    domain: security
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: homelab
  sources:
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
      chart: secrets-operator
      targetRevision: 0.10.2
      helm:
        releaseName: secrets-operator
    - repoURL: https://github.com/Brsalcedom/homelab-iac
      path: k8s/applications/argocd/infisical/manifests
      targetRevision: main
      ref: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true