apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird
  namespace: netbird
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netbird
  template:
    metadata:
      labels:
        app: netbird
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 192.168.1.150
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - home.cervant.net
      containers:
        - name: netbird
          image: netbirdio/netbird:latest
          env:
            - name: NB_SETUP_KEY
              value: "XXX-XXX-XXX-XXX"
            - name: NB_HOSTNAME
              value: "k3s"
            - name: NB_LOG_LEVEL
              value: "info"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_RESOURCE
                - SYS_ADMIN
