apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    tier: controllers
    domain: security
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: homelab
  sources:
    - repoURL: https://external-secrets.io
      chart: external-secrets
      targetRevision: "0.19.2"
      helm:
        values: |
          bitwarden-sdk-server:
            enabled: true
    - repoURL: https://github.com/Brsalcedom/homelab-iac.git
      targetRevision: main
      path: k8s/applications/argocd/external-secrets/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true