    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: infisical-route
      namespace: infisical
    spec:
      parentRefs:
        - name: cilium-gateway
          namespace: cilium-gateway
          sectionName: "https"
      hostnames:
      - "infisical.home.cervant.net"
      rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - name: infisical-standalone-infisical
            port: 8080