apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml

patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: infisical-secrets
  - target:
      kind: Deployment
      name: infisical-standalone-infisical
      namespace: infisical