apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infisical-postgresql
  namespace: infisical
  labels:
    app: infisical-postgresql
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-standard-bullsey
  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: local-path
      volumeMode: Filesystem