services:
  mongo:
    image: mongo:7
    container_name: komodo-mongo
    command:
      - --quiet
      - --wiredTigerCacheSizeGB
      - ${MONGO_CACHE_GB:-0.25}
    restart: unless-stopped
    volumes:
      - komodo-mongo-data:/data/db
      - komodo-mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DB_PASSWORD}

  core:
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo-core
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "${KOMODO_CORE_PORT:-9120}:9120"
    volumes:
      - ./config.toml:/config/config.toml:ro
      - ${COMPOSE_KOMODO_BACKUPS_PATH:-./komodo-backups}:/backups

  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    container_name: komodo-periphery
    restart: unless-stopped
    depends_on:
      - core
    environment:
      PERIPHERY_ROOT_DIRECTORY: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
      PERIPHERY_PASSKEYS: ${PERIPHERY_PASSKEYS}
      PERIPHERY_DISABLE_TERMINALS: ${PERIPHERY_DISABLE_TERMINALS:-false}
      PERIPHERY_INCLUDE_DISK_MOUNTS: ${PERIPHERY_INCLUDE_DISK_MOUNTS:-/etc/hostname}
      PERIPHERY_SSL_ENABLED: ${PERIPHERY_SSL_ENABLED:-true}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    ports:
      - "${PERIPHERY_PORT:-8120}:8120"

volumes:
  komodo-mongo-data:
  komodo-mongo-config:
