apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  labels:
    tier: controllers
    domain: security
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: homelab
  sources:
    - repoURL: https://charts.jetstack.io
      chart: trust-manager
      targetRevision: "v0.19.0"
      helm:
        values: |
          crds:
            enabled: true
    - repoURL: https://github.com/Brsalcedom/homelab-iac.git
      targetRevision: main
      path: k8s/applications/argocd/trust-manager/manifests
      ref: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true