apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://gitlab.com/bryansalcedo/homelab-argocd.git
    targetRevision: main
    path: apps/netbird/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: netbird
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
