apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird
  namespace: argocd
  labels:
    tier: platform
    domain: networking
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: homelab
  source:
    repoURL: https://github.com/Brsalcedom/homelab-iac.git
    targetRevision: main
    path: k8s/applications/argocd/netbird/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: netbird
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
