name: PR assignment

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - name: 'Auto-assign PR'
        uses: pozil/auto-assign-issue@v2.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: Brsalcedom
